services:
  - type: web
    name: interviewai-backend
    runtime: docker
    repo: https://github.com/srikar-1810/Ai-Interviewer
    region: oregon
    plan: free
    branch: main
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: BACKEND_URL
        value: https://ai-interviewer-7w1u.onrender.com
      - key: FRONTEND_URL
        value: https://ai-interviewer-7w1u.onrender.com
      - key: USE_REMOTE_DATABASE
        value: "true"
      - key: DATABASE_URL
        sync: false
